import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/global.css";
import BottomTab from "@/components/common/BottomTab";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        {children}
        <BottomTab />
      </body>
    </html>
  );
}
